# Site settings
title: "md"
bye_message: "Thx!"
baseurl: "/"
url: "https://mucahiddogan.github.io"
disqus:

# Header settings
nick: "md"
mail:
    domain: "protonmail"
    ext: "com"
source_code:
    server: "github.com"
    nick: "mucahiddogan"
blog:
    server: "wordpress.com"
    nick: "mucahiddogan"
fingerprint_key: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
